### ISSUE TITLE
Странная конструкция

### ISSUE THREAD

**Issue by ubcent** [mgolovkina/JavaScript#1]
[L94](https://github.com/mgolovkina/JavaScript/blob/master/lesson2/chess.html#L94) Странная конструкция :smile: поясните пожалуйста

**Comment by mgolovkina** [comment]
Переменная row содержит строку с номером ряда в таблице. Конструкция +row преобразовывает строку в число. Таким образом я увеличиваю номер ряда: +row + 1. Иначе выражение row + 1 выполнить конкатенацию.
